[versions]
compose = "1.12.1"
coroutines = "1.11.0"
flatlaf = "3.7.2"
jna = "5.19.1"
zxing = "3.5.4"

[libraries]
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "coroutines" }
flatlaf = { module = "com.formdev:flatlaf", version.ref = "flatlaf" }
jna-platform = { module = "net.java.dev.jna:jna-platform", version.ref = "jna" }
zxing-core = { module = "com.google.zxing:core", version.ref = "zxing" }

[plugins]
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
